---
title: "Scholarly Publications"
format: html
editor: visual
---

Browse scholarly publications researched and authored by the County Health Rankings team and other researchers on a variety of topics related to population health and equity.

## Community Action and Guidance 

Hirsch, B. K., Frobom, K. E., Giglierano, G., Stevenson, M. C., & Givens, M. L. (2025). [Centering equity in evidence-informed decision-making: Theoretical and practical considerations.](https://onlinelibrary.wiley.com/doi/10.1111/1468-0009.70002) Milbank Quarterly, 103(1), 11-31. https://doi.org/10.1111/1468-0009.70002

Hirsch, B. K., Stevenson, M. C., & Givens, M. L. (2023). [Evidence clearinghouses as tools to advance health equity: What we know from a systematic scan](https://link.springer.com/article/10.1007/s11121-023-01511-7). *Prevention Science*, 24(4), 613–624. https://doi.org/10.1007/s11121-023-01511-7

Willems Van Dijk, J. A., Catlin, B., Cofsky, A., & Carroll, C. (2015). [Challenges and lessons learned from communities using evidence to adopt strategies to improve healthy food environments](https://www.healthaffairs.org/doi/10.1377/hlthaff.2015.0643?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed). *Health Affairs*, 34(11), 1979–1985. https://doi.org/10.1377/hlthaff.2015.0643

Bergum, A., Grigg, L., Givens, M. L., Catlin, B. B., & Willems Van Dijk, J. (2019). [How to be an informed consumer of evidence ratings: It’s in the details](https://www.cdc.gov/pcd/issues/2019/19_0067.htm). *Preventing Chronic Disease*, 16. https://doi.org/10.5888/pcd16.190067

## Rankings Rationale and History 

County Health Rankings & Roadmaps. (2025). [*County Health Rankings & Roadmaps working paper: Updates to methods and tools for practical application to improve health and equity*](files/WorkingPaperCHRR2025.pdf). University of Wisconsin Population Health Institute.

Catlin, B. B., & Willems Van Dijk, J. A. (2020). [*Ten-year reflections on the County Health Rankings & Roadmaps. University of Wisconsin Population Health Institute*](files/CHRR10_year_reflections_report.pdf).

Purtle, J., Peters, R., Kolker, J., & Diez Roux, A. V. (2019). [Uses of population health rankings in local policy contexts: A multisite case study](https://www.countyhealthrankings.org/sites/default/files/Purtle_et_al_CHR_MCRR_2017.pdf). *Medical Care Research and Review*, 76(4), 478–496. https://doi.org/10.1177/1077558717726115

Booske, B. C., Athens, J. K., Kindig, D. A., Park, H., & Remington, P. L. (2010, February). [*County Health Rankings working paper: Different perspectives for assigning weights to determinants of health*.](files/differentPerspectivesForAssigningWeightsToDeterminantsOfHealth.pdf) University of Wisconsin Population Health Institute.

Remington, P. L., Catlin, B. B., & Gennuso, K. P. (2015). [The county health rankings: Rationale and methods](http://www.pophealthmetrics.com/content/13/1/11). *Population Health Metrics*, 13(1), 11. https://doi.org/10.1186/s12963-015-0044-2

Remington, P. L. (2015). [County health rankings and the cult of the imperfect](https://www.countyhealthrankings.org/sites/default/files/Remington_HealthServRes_2015.pdf). *Health Services Research*, 50(5), 1407–1412. https://doi.org/10.1111/1475-6773.12351

Remington, P. L., & Booske, B. C. (2011). [Measuring the health of communities—How and why?](http://journals.lww.com/jphmp/toc/2011/09000) *Journal of Public Health Management and Practice*, 17(5), 397. https://doi.org/10.1097/PHH.0b013e318222b897

Rohan, A. M. K., Booske, B. C., & Remington, P. L. (2009). [Using the Wisconsin County Health Rankings to catalyze community health improvement](http://journals.lww.com/jphmp/Abstract/2009/01000/Using_the_Wisconsin_County_Health_Rankings_to.5.aspx). *Journal of Public Health Management and Practice*, 15(1), 24. https://doi.org/10.1097/PHH.0b013e3181903bf8

Peppard, P. E., Kindig, D. A., Dranger, E., Jovaag, A., & Remington, P. L. (2008). [Ranking community health status to stimulate discussion of local public health issues: The Wisconsin County Health Rankings](http://ajph.aphapublications.org/cgi/reprint/98/2/209.pdf). *American Journal of Public Health*, 98(2), 209–212. https://doi.org/10.2105/AJPH.2006.092981

## Rankings Methods and Results 

Pollock, E. A., Gangnon, R. E., Gennuso, K. P., & Givens, M. L. (2024). [Cluster analysis methods to support population health improvement among U.S. counties. Journal of Public Health Management and Practice](https://journals.lww.com/jphmp/abstract/9900/cluster_analysis_methods_to_support_population.310.aspx), 30(6), E319. https://doi.org/10.1097/PHH.0000000000002034

Nguyen, T. Q., Michaels, I. H., Bustamante-Zamora, D., Waterman, B., Nagasako, E., Li, Y., Givens, M. L., & Gennuso, K. (2021).[ Generating subcounty health data products: Methods and recommendations from a multistate pilot initiative](https://pubmed.ncbi.nlm.nih.gov/32332489/). *Journal of Public Health Management and Practice*: JPHMP, 27(1), E40–E47. https://doi.org/10.1097/PHH.0000000000001167

Park, H., Roubal, A. M., Jovaag, A., Gennuso, K. P., & Catlin, B. B. (2015). [Relative contributions of a set of health factors to selected health outcomes](https://www.countyhealthrankings.org/sites/default/files/Park_AmJPrevMed_2015.pdf). *American Journal of Preventive Medicine*, 49(6), 961–969. https://doi.org/10.1016/j.amepre.2015.07.016

Hood, C. M., Gennuso, K. P., Swain, G. R., & Catlin, B. B. (2016). County health rankings: [Relationships between determinant factors and health outcomes](https://www.sciencedirect.com/science/article/pii/S0749379715005140). *American Journal of Preventive Medicine*, 50(2), 129–135. https://doi.org/10.1016/j.amepre.2015.08.024

Athens, J. K., Remington, P. L., & Gangnon, R. E. (2015).[ Improving the rank precision of population health measures for small areas with longitudinal and joint outcome models](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0130027&type=printable). *PLOS ONE*, 10(6), e0130027. https://doi.org/10.1371/journal.pone.0130027

Roubal, A. M., Jovagg, A., Park, H., & Gennuso, K. P. (2015). [Development of a nationally representative built environment measure of access to exercise opportunities.](https://www.cdc.gov/pcd/issues/2015/14_0378.htm) *Preventing Chronic Disease*, 12. https://doi.org/10.5888/pcd12.140378

Athens, J. K., Catlin, B. B., Remington, P. L., & Gangnon, R. E. (2013). [Using empirical bayes methods to rank counties on population health measures](https://www.cdc.gov/pcd/issues/2013/pdf/13_0028.pdf). *Preventing Chronic Disease*, 10, E129. https://doi.org/10.5888/PCD10.130028

Arndt, S., Acion, L., Caspers, K., & Blood, P. (2013). [How reliable are county and regional health rankings?](https://www.ncbi.nlm.nih.gov/pubmed/23400846) *Prevention Science: The Official Journal of the Society for Prevention Research*, 14(5), 497–502. https://doi.org/10.1007/s11121-012-0320-3

## County-Level Analysis 

Donneyong, M. M., Chang, T.-J., Jackson, J. W., Langston, M. A., Juarez, P. D., Sealy-Jefferson, Lu, B., Im, W., Valdez, R. B., Way, B. M., Colen, C., Fischer, M. A., Salsberry, P., Bridges, J. F. P., & Hood, D. B. (2020). [Structural and social determinants of health factors associated with county-level variation in non-adherence to antihypertensive medication treatment](https://www.countyhealthrankings.org/sites/default/files/media/document/International_Journal_of_Environmental_Research_and_Public_Health_2020.pdf). *International Journal of Environmental Research and Public Health*, 17(18), 6684. https://doi.org/10.3390/ijerph17186684

Gennuso, K. P., Blomme, C. K., Givens, M. L., Pollock, E. A., & Roubal, A. M. (2019). [Deaths of despair(ity) in early 21st century America: The rise of mortality and racial/ethnic disparities](https://www.ajpmonline.org/article/S0749-3797(19)30305-8/fulltext). *American Journal of Preventive Medicine*, 57(5), 585–591. https://doi.org/10.1016/j.amepre.2019.06.018

Nagasako, E., Waterman, B., Reidhead, M., Lian, M., & Gehlert, S. (2018). [Measuring subcounty differences in population health using hospital and census-derived data sets: The Missouri ZIP health rankings project](https://journals.lww.com/jphmp/Fulltext/2018/07000/Measuring_Subcounty_Differences_in_Population.8.aspx). *Journal of Public Health Management & Practice*, 24(4). 340 – 349. https://doi.org/10.1097/PHH.0000000000000578

McCullough, J. M., & Leider, J. P. (2017). [Associations between county wealth, health and social services spending, and health outcomes](https://www.ncbi.nlm.nih.gov/pubmed/28688726). *American Journal of Preventive Medicine*, 53(5), 592–598. https://doi.org/10.1016/j.amepre.2017.05.005

Gennuso, K. P., Jovaag, A., Catlin, B. B., Rodock, M., & Park, H. (2016). [Assessment of factors contributing to health outcomes in the eight states of the Mississippi Delta region](https://www.cdc.gov/pcd/issues/2016/15_0440.htm). *Preventing Chronic Disease*, 13, 150440. https://doi.org/10.5888/pcd13.150440

Lin, Y. H., Eberth, J. M., & Probst, J. C. (2016). [Ambulatory care-sensitive hospitalizations among Medicare beneficiaries](https://www.ajpmonline.org/article/S0749-3797(16)30143-X/fulltext). *American Journal of Preventive Medicine*, 51(4), 493–501. https://doi.org/10.1016/j.amepre.2016.05.005

McCullough, J. M., & Leider, J. P. (2016). [Government spending in health and nonhealth sectors associated with improvement in county health rankings](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.2016.0708?sid=cb50a4a1-221d-456d-bf9f-d07df4095409). *Health Affairs*, 35(11), 2037–2043. https://doi.org/10.1377/hlthaff.2016.0708

Greer, S., Schieb, L. J., Ritchey, M., George, M., & Casper, M. (2016). [County health factors associated with avoidable deaths from cardiovascular disease in the United States, 2006-2010](https://journals.sagepub.com/doi/pdf/10.1177/003335491613100310). *Public Health Reports*, 131(3), 438–448.  https://journals.sagepub.com/doi/pdf/10.1177/003335491613100310

Hardin-Fanning, F., & Wiggins, A. T. (2017). [Food costs are higher in counties with poor health rankings](https://www.ncbi.nlm.nih.gov/pubmed/26977851). *Journal of Cardiovascular Nursing*, 32(2), 93–98. https://doi.org/10.1097/JCN.0000000000000329

Peyer, K., Welk, G. J., Bailey-Davis, L., & Chen, S. (2016).[ Relationships between county health rankings and child overweight and obesity prevalence: A serial cross-sectional analysis](https://www.countyhealthrankings.org/sites/default/files/Peyer_BMC_Public_Health_2016.pdf). *BMC Public Health*, 16, 404.\
https://doi.org/10.1186/s12889-016-3091-0

Anderson, T. J., Saman, D. M., Lipsky, M. S., & Lutfiyya, M. N. (2015). [A cross-sectional study on health differences between rural and non-rural U.S. counties using the county health rankings](https://www.countyhealthrankings.org/sites/default/files/Anderson_Health%20Serv%20Res_2015.pdf). *BMC Health Services Research*, 15, 441. https://doi.org/10.1186/s12913-015-1053-3

Fields, B. E., Bigbee, J. L., & Bell, J. F. (2015). [Associations of provider-to-population ratios and population health by county-level rurality](https://onlinelibrary.wiley.com/doi/full/10.1111/jrh.12143). *Journal of Rural Health*, 32(3), 235–244. https://doi.org/10.1111/jrh.12143

Winterbauer, N. L., Rafferty, P. L., Tucker, A., Jones, K., & Tucker-McLaughlin, M. (2016). [Use and perceived impact of the county health rankings report in Florida and North Carolina](https://www.ncbi.nlm.nih.gov/pubmed/26295197). *Journal of Public Health Management & Practice*, 22(6), E1-E7. https://doi.org/10.1097/phh.0000000000000320

Courtemanche, C., Soneji, S., & Tchernis, R. (2015).[ Modeling area-level health rankings](https://www.countyhealthrankings.org/sites/default/files/Courtemanche_HealthServRes_2015.pdf). *Health Services Research*, 50(5), 1413-1431. https://doi.org/10.1111/1475-6773.12352

Hoffman, G. J., & Rodriguez, H. P. (2015). [Examining contextual influences on fall-related injuries among older adults for population health management](https://www.ncbi.nlm.nih.gov/pubmed/25919228). *Population Health Management*, 18(6), 437–448. https://doi.org/10.1089/pop.2014.0156

Singh, S. R., Young, G. J., Lee, S. Y. D., Song, P. H., & Alexander, J. A. (2015). [Analysis of hospital community benefit expenditures' alignment with community health needs: Evidence from a national investigation of tax-exempt hospitals](https://ajph.aphapublications.org/doi/full/10.2105/AJPH.2014.302436). *American Journal of Public Health*, 105(5), 914–921.  https://doi.org/10.2105/AJPH.2014.302436

Harris, A. L., Scutchfield, F. D., Heise, G., & Ingram, R. C. (2014). [The relationship between local public health agency administrative variables and county health status rankings in Kentucky](https://www.ncbi.nlm.nih.gov/pubmed/24435012). *Journal of Public Health Management & Practice*, 20(4), 378–383. https://doi.org/10.1097/PHH.0b013e3182a5c2f8

Holzer, J., Canavan, M., & Bradley, E. (2014). [County-level correlation between adult obesity rates and prevalence of dentists](https://www.ncbi.nlm.nih.gov/pubmed/25170000). *Journal of the American Dental Association*, 145(9), 932–939. https://doi.org/10.14219/jada.2014.48

Kindig, D. A., & Cheng, E. (2013). [Even as mortality fell in most U.S. counties, female mortality nonetheless rose in 42.8 percent of counties from 1992 to 2006](https://www.healthaffairs.org/doi/pdf/10.1377/hlthaff.2011.0892). *Health Affairs*, 32(3), 451–458. https://doi.org/10.1377/hlthaff.2011.0892

Cheng, E., & Kindig, D. A. (2012). [Disparities in premature mortality between high- and low-income U.S. counties](https://www.cdc.gov/pcd/issues/2012/11_0120.htm). *Preventing Chronic Disease*, 9(3), 110120. http://dx.doi.org/10.5888/pcd9.110120

## Mobilizing Action for Community Health (MATCH) Series 

Kindig, D. A., Catlin, B. B., & Remington, P. L. (2010). Mobilizing action toward community health (MATCH): Metrics, incentives, and partnerships for population health. *Preventing Chronic Disease*, 7(4): A68. [http://www.cdc.gov/pcd/issues/2010/jul/10_0019.htm](https://www.cdc.gov/pcd/issues/2010/jul/10_0019.htm)

Pestronk, R. M. (2010). Using metrics to improve population health. Preventing Chronic Disease, 7(4): A70. [http://www.cdc.gov/pcd/issues/2010/jul/10_0018.htm](https://www.cdc.gov/pcd/issues/2010/jul/10_0018.htm)

Bilheimer, L. T. (2010). Evaluating metrics to improve population health. Preventing Chronic Disease, 7(4): A69. [http://www.cdc.gov/pcd/issues/2010/jul/10_0016.htm](https://www.cdc.gov/pcd/issues/2010/jul/10_0016.htm)

Oliver, T. R. (2010). Population health rankings as policy indicators and performance measures. Preventing Chronic Disease, 7(5), A101. <https://www.cdc.gov/pcd/issues/2010/sep/pdf/10_0040.pdf>

Parrish, R. G. (2010). Measuring population health outcomes. Preventing Chronic Disease, 7(4): A71. [http://www.cdc.gov/pcd/issues/2010/jul/10_0005.htm](https://www.cdc.gov/pcd/issues/2010/jul/10_0005.htm)

Asada, Y. (2010). A summary measure of health inequalities for a pay-for-population health performance system. Preventing Chronic Disease, 7(4): A72. [http://www.cdc.gov/pcd/issues/2010/jul/09_0250.htm](https://www.cdc.gov/pcd/issues/2010/jul/09_0250.htm)

Kottke, T. E., & Isham, G. J. (2010). Measuring health care access and quality to improve health in populations. Preventing Chronic Disease, 7(4): A73. [http://www.cdc.gov/pcd/issues/2010/jul/09_0243.htm](https://www.cdc.gov/pcd/issues/2010/jul/09_0243.htm)

Lantz, P. M., & Pritchard, A. (2010). Socioeconomic indicators that matter for population health. Preventing Chronic Disease, 7(4): A74. [http://www.cdc.gov/pcd/issues/2010/jul/09_0246.htm](https://www.cdc.gov/pcd/issues/2010/jul/09_0246.htm)

Mokdad, A. H., & Remington, P. L. (2010). Measuring health behaviors in populations. Preventing Chronic Disease, 7(4): A75. [http://www.cdc.gov/pcd/issues/2010/jul/10_0010.htm](https://www.cdc.gov/pcd/issues/2010/jul/10_0010.htm)

Jakubowski, B., & Frumkin, H. (2010). Environmental metrics for community health improvement. Preventing Chronic Disease, 7(4): A76.  [http://www.cdc.gov/pcd/issues/2010/jul/09_0242.htm](https://www.cdc.gov/pcd/issues/2010/jul/09_0242.htm)

Brownson, R. C., Seiler, R., & Eyler, A. A. (2010). Measuring the impact of public health policy. Preventing Chronic Disease, 7(4): A77. [http://www.cdc.gov/pcd/issues/2010/jul/09_0249.htm](https://www.cdc.gov/pcd/issues/2010/jul/09_0249.htm)
